### ISSUE TITLE
Uvicorn shall not watch for changes in files in the integration test folder

### ISSUE THREAD

**Issue by mettta** [strictdoc-project/strictdoc#1011]

**Comment by stanislaw** [comment]
It looks like it is not possible to isolate the uvicorn working in the reload mode from the integration tests running in a parallel terminal window. I have reported a configuration issue around these lines to the uvicorn's Gitter chat.

https://github.com/encode/uvicorn/commit/b1a45821a2ab916b4428bdcb9eba4a4a0cc8fb74#diff-b05583f76145cb1bc7a64eeb0328c2e7d1cc6693aa72bbc4f61ca6f332751073R68-R72
