### ISSUE TITLE
Form validation for grammar fields that are marked as required

### ISSUE THREAD

**Issue by mettta** [strictdoc-project/strictdoc#1022]
Currently, it is possible to save a required field with an empty value because there is no corresponding validation.

The right behaviour is to prevent required fields from being saved when they are empty.

```
error: could not parse file: /Users/mettta/Projects/dev/strictdoc/docs/strictdoc_20_requirements.sdoc.

Semantic error: Wrong field order for requirement: [UID, REFS, STATEMENT]
Location: /Users/mettta/Projects/dev/strictdoc/docs/strictdoc_20_requirements.sdoc:37:1
Hint: Problematic field: STATEMENT. Compare with the document grammar: [UID, REFS, TITLE, STATEMENT, RATIONALE, COMMENT] for type: REQUIREMENT
```

**Comment by stanislaw** [comment]
I believe this has been fixed by the recent work in https://github.com/strictdoc-project/strictdoc/pull/1299.

**Comment by stanislaw** [comment]
This ticket can be done together with https://github.com/strictdoc-project/strictdoc/issues/1076.
