### ISSUE TITLE
Implement the initial SDoc markup highlighting plugin for Visual Studio Code

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#1059]

**Comment by mettta** [comment]
Repo: [strictdoc.tmLanguage](https://github.com/strictdoc-project/strictdoc.tmLanguage)
Extension in Marketplace: [StrictDoc Language Basics Extension](https://marketplace.visualstudio.com/items?itemName=StrictDoc.strictdoc)
