### ISSUE TITLE
Several errors with strictdoc server, possibly connected to deployment via PyInstaller

### ISSUE THREAD

**Issue by RobertoBagnara** [strictdoc-project/strictdoc#1068]
Here is a small selection (from run A):

INFO:     [127.0.0.1:41282](http://127.0.0.1:41282/) - "GET /_static/controllers/movable_field_controller.js HTTP/1.1" 404 Not Found
INFO:     [127.0.0.1:41286](http://127.0.0.1:41286/) - "GET /_static/controllers/modal_controller.js HTTP/1.1" 404 Not Found
INFO:     [127.0.0.1:41286](http://127.0.0.1:41286/) - "GET /_static/turbo.js HTTP/1.1" 404 Not Found
INFO:     [127.0.0.1:41282](http://127.0.0.1:41282/) - "GET /_static/stimulus.js HTTP/1.1" 404 Not Found
INFO:     [127.0.0.1:55670](http://127.0.0.1:55670/) - "GET /actions/document/new_section?reference_mid=5b5f8ff1d6bf4e8fb75fa1a9aeaf10f7&whereto=before HTTP/1.1" 200 OK
INFO:     connection closed
INFO:     [127.0.0.1:55670](http://127.0.0.1:55670/) - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     [127.0.0.1:55670](http://127.0.0.1:55670/) - "GET /_static/viewtype_menu.js HTTP/1.1" 404 Not Found
INFO:     [127.0.0.1:55678](http://127.0.0.1:55678/) - "GET /_static/toc.js HTTP/1.1" 404 Not Found
INFO:     [127.0.0.1:54640](http://127.0.0.1:54640/) - "GET /_static/controllers/collapsible_list_controller.js HTTP/1.1" 404 Not Found
INFO:     ('127.0.0.1', 54648) - "WebSocket /ws/1679579996493" [accepted]
INFO:     connection open
INFO:     [127.0.0.1:54640](http://127.0.0.1:54640/) - "GET /actions/document/new_requirement?reference_mid=5b5f8ff1d6bf4e8fb75fa1a9aeaf10f7&whereto=after HTTP/1.1" 500 Internal Server Error

Here is the full log (from run B):

[LOG.txt](https://github.com/strictdoc-project/strictdoc/files/11053054/LOG.txt)

**Comment by stanislaw** [comment]
Please also provide:

- the exact command
- which folder you are running you are running
- which documents you have in the folder.

This should help me to reproduce the case.

**Comment by RobertoBagnara** [comment]
Command is
```
    ./strictdoc server ~/eclair/demos/Linux/GCC/ECLAIR-3.13_demo_eclair_reqman_Unix_GCC/Sorting.sdoc
``

Current directory is the same directory where the PyInstaller stuff is installed.

Document is attached (the `.txt` suffix has been added just for being able of attaching it):

[Sorting.sdoc.txt](https://github.com/strictdoc-project/strictdoc/files/11053250/Sorting.sdoc.txt)

**Comment by curiousmuch** [comment]
I saw this originally on my linux install. I was using adsf + pipx. I reshimed and re-installed w/ pipx. I believe I also restarted the shell and I saw the issue went away.

**Comment by Abramo-Bagnara** [comment]
What I've observed is that _static folder is searched under strictdoc/export/html while it is present in the same folder of strictdoc executable.

Adding a symbolic link the pages are shown correctly, with a few residual bugs:

1) editing a requirement of Sorting.sdoc file above the server show an exception about field COVERAGE_SINGLE
2) editing the grammar all fields are set to REQUIRED=False and TYPE=String

**Comment by stanislaw** [comment]
Thanks for the extra input! This issue is next in my queue. I should get to it this evening.

**Comment by stanislaw** [comment]
@RobertoBagnara and @Abramo-Bagnara,

Please give the latest main branch a try. The paths should now be resolved correcly. I am not releasing a new Pip because you are building with PyInstaller anyway.

With regard to your further comments, I have documented better that the UI does not support `SingleChoice` field yet (hence the NotImplementedError). For now, you should promote your choice field back to a string field.

**Comment by stanislaw** [comment]
And one more comment regarding the `Required`. Yes, currently the server hardcodes to Required: False because the necessary UI framework is still missing for implementing the editable `True/False` options and similar. For now, if you want to use the UI, the grammar can only have all non-optional fields.
