### ISSUE TITLE
Cannot execute strictdoc command 

### ISSUE THREAD

**Issue by matteotoma98** [strictdoc-project/strictdoc#1070]
![image](https://user-images.githubusercontent.com/48352371/227275341-6ad7ffb0-b901-4d8d-86c6-6e70f58c8040.png)

I installed strictdoc by pip, and when i put the command strictdoc export --help it don't recognize it.
I also added the path in which strictodc was insalled (C:\Users\matte\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages)

I'm using Windows 11 btw

**Comment by stanislaw** [comment]
Hi @matteotoma98,

Today, another user has reported that they are running StrictDoc on Windows successfully.

Before we start suspecting StrictDoc, could you try any other Python package and see if you can access it via your PATH? Try this for example: 

```
pip install docstrfmt
docstrfmt
```

**Comment by matteotoma98** [comment]
After i runned first command, it finished but during installation it says:
  WARNING: The script tabulate.exe is installed in 'C:\Users\matte\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Attempting uninstall: docutils
    Found existing installation: docutils 0.19
    Uninstalling docutils-0.19:
      Successfully uninstalled docutils-0.19
  WARNING: The script normalizer.exe is installed in 'C:\Users\matte\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pybabel.exe is installed in 'C:\Users\matte\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts black.exe and blackd.exe are installed in 'C:\Users\matte\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts sphinx-apidoc.exe, sphinx-autogen.exe, sphinx-build.exe and sphinx-quickstart.exe are installed in 'C:\Users\matte\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts docstrfmt.exe and docstrfmtd.exe are installed in 'C:\Users\matte\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  
  
  and then when i run docstrfmt is not recognized.
  
  
After adding the path in windows environment variability, I fixed. thank you.

**Comment by stanislaw** [comment]
Do I understand it right, that `strictdoc` command is now working for you? If so, please close this issue and open another one if you have further questions!
