### ISSUE TITLE
Populating and auto-incrementing requirement UID automatically

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#1081]
Currently, the UIDs have to be created manually by a user. It would be great to support the dynamic assignment of the UIDs.

The following options are available:

- Increment-based mask: `REQ-` part is provided and then `REQ-1`, `REQ-2`, `REQ-3`, ...

  - Another option: Mask-based with reservation: `REQ-XXXXXX`. Producing `REQ-000001`, `REQ-000002`, ... (considered for implementation)
    - (This behavior is what Requirements Yogi plugin implements but for StrictDoc, unless there is a strong request, we would not do this fixed mask behavior.)

- UUID-based mask:
  - Which UID format use?
    - `md5` or `SHA1` (considered for implementation)
    - Option: longer but not too long hash identifiers, similar to commit hashes, e.g., `4525fee`.
  - How to deal with having several masks in the same document? Mask could be specified on the document level and on the section level? 

There should be a CLI command and the UI button to auto-generate the identifiers according to the chosen mask option. The option should work per document.

## Command-line interface

- **"Generate new ID"** command:
  - Works per document.
  - For incremental mask, prints the next ID.
  - For UUID mask, prints the next random UUID.
  - A user has to take the UID and fill it in manually.

- **"Auto-fill all requirements with missing UID"** command:
  - Works per document.
  - For incremental mask, it traverses all requirements from beginning to end and adds the UID, incrementing the next number all the time. The sequential order of the generation is not enforced.
  - For random UID mask, a random UID is created all the time.

## UI interface

When a requirement is being created or edited:

- The UI reports on each keystroke on whether an existing UID is taken already or not.
- The UI suggests the next UID nearby the field: `Fill in automatically: NEXT-ID`.

For the document / section: there is a button "Generate UID automatically", and the behavior depends on the mask chosen per document or section.

**Comment by stanislaw** [comment]
The CLI part of this ticket is on its way: https://github.com/strictdoc-project/strictdoc/pull/1184.

**Comment by mettta** [comment]
It looks like we have implemented all of this in several MRs. The only task left is to create Sections UID using the incremental numeric algorithm (#1538).
