### ISSUE TITLE
Empty statement error

### ISSUE THREAD

**Issue by elfman2** [strictdoc-project/strictdoc#1083]
Since 0.0.34

[DOCUMENT]
TITLE: Title

[REQUIREMENT]
TITLE: Title
STATEMENT:

Generates
file "/usr/local/lib/python3.9/dist-packages/strictdoc/backend/sdoc/models/requirement.py", line 355, in _get_cached_field
    raise NotImplementedError(self)
NotImplementedError: Requirement(requirement_type = "REQUIREMENT", fields = [2 elements], _tx_position = 25, _tx_position_end = 64, parent = Document(...), references = [], requirements = NoneType(...), has_meta = False, fields_as_parsed = [2 elements], ordered_fields_lookup = OrderedDict(2 elements), ng_level = 1, ng_document_reference = DocumentReference(...), context = RequirementContext(...), node_id = "e0914a64b41d4a4c8823790c0e8e0e8a", ng_resolved_custom_level = NoneType(...), custom_level = NoneType(...), ng_reserved_fields_cache = {3 elements})
error: Parallelizer: One of the child processes has exited prematurely.

**Comment by stanislaw** [comment]
Hi @elfman2, thanks for reporting this.

This is a known issue which we wanted to handle together with another related issue but simply didn't find a good time: https://github.com/strictdoc-project/strictdoc/issues/823. Your report helps us to give it a higher priority.

I am going to work on it this week.
