### ISSUE TITLE
Warnings during tests: deprecated tools and requests to update to Node.js 16 and to using Environment Files.

### ISSUE THREAD

**Issue by mettta** [strictdoc-project/strictdoc#1101]
Jobs:
E2E - Linux (3.7) 
E2E - Windows (3.7)

```Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.```

```The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/```

**Comment by stanislaw** [comment]
Closed some time ago by #1150.
