### ISSUE TITLE
.. image:: filename.* not rendered

### ISSUE THREAD

**Issue by elfman2** [strictdoc-project/strictdoc#1106]
The directive is not rendered with **export html**, but is rendered ok with **--format rst** then _sphinx_.
This is typically required for compatible pdf and html export.
for pdf export, svg images are converted to .pdf with for instance  _cairosvg_

.. image:: filename.* makes .sdoc compatible with both:

.. image:: filename.svg for html 
and 
.. image:: filename.pdf for pdflatex

**Comment by stanislaw** [comment]
I am not sure if I fully understood your report. Are you saying that `.. image::` does not get rendered with export html at all or it is not rendered under a certain condition?

I have double-checked the examples here: https://github.com/strictdoc-project/strictdoc-examples. The [image example](https://github.com/strictdoc-project/strictdoc-examples/blob/main/examples/example_05.sdoc) is working for me. Could you check it as well or report more specifically what exactly is not working for you?

Also, I have fixed [another RST issue today](https://github.com/strictdoc-project/strictdoc/pull/1107), so you may want to `pip install -U strictdoc` just to make sure you were not affected by that one.

**Comment by elfman2** [comment]
[This is linked to a sphinx extension which I guess is not in docutils](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#images)

```
Sphinx extends the standard docutils behavior by allowing an asterisk for the extension:

.. image:: gnu.*
```

Indeed .svg is not supported by sphinx/pdflatex => .* extension enables to be both compatible with html and pdf.
I could use a concrete extension (.svg) in the .sdoc, and post process it to feed into sphinx for pdflatex generation..
