### ISSUE TITLE
Fix node markup for REQUIREMENTS COVERAGE

### ISSUE THREAD

**Issue by mettta** [strictdoc-project/strictdoc#1111]
While doing this ticket (the screenshot is above), consider also doing this one at the same time: https://github.com/strictdoc-project/strictdoc/issues/510.

---

![image](https://user-images.githubusercontent.com/490084/231863984-0f761a26-a32c-44cd-8501-ed36bdfb5170.png)

**Comment by stanislaw** [comment]
We may want to reconsider the function and the design of this screen given the work we have to do for #964.

**Comment by stanislaw** [comment]
No longer actual due to https://github.com/strictdoc-project/strictdoc/pull/1531.
