### ISSUE TITLE
pip install fails on win10 due to short path in windows registry

### ISSUE THREAD

**Issue by elfman2** [strictdoc-project/strictdoc#1118]
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '...\pip-install-9q1zkcnm\\strictdoc_e6f8310587ee4b20b1532ccdaf79efaa\\tests/end2end/screens/document/UC07_edit_requirement/UC07_G1_editing_requirement_links/UC07_G1_T10_editing_requirement_refs_validate_empty/test_UC07_G1_T10_editing_requirement_refs.py'
HINT: This error might have occurred since this system does not have Windows Long Path support enabled. You can find information on how to enable this at https://pip.pypa.io/warnings/enable-long-paths

NB: requires admin privilege to change registry

**Comment by stanislaw** [comment]
Thanks for reporting this!

Does it mean that it is possible to install on Windows but that Long Path support has to be enabled? Should we add this to the "Getting started" instructions for Windows?

A few comments to this:

1) The Pip package doesn't need to have the end-to-end tests bundled in. It could be a good idea to investigate a config option in pyproject.yml to allow that.
2) Our e2e file names are verbose for a good reason but we were thinking of trimming the naming conventions down a little bit. This, however, will not guarantee that this problem will not appear for all cases.
