### ISSUE TITLE
Feature request: support include_directories and exclude_directories option for traceability

### ISSUE THREAD

**Issue by Minipada** [strictdoc-project/strictdoc#1157]
Currently, the traceability feature tracks all files in the directory by default.
The use case is that I would like to connecting tests to requirements (test based requirements) and all my tests are under

dir1/test
dir2/test
...
and i have the main code in dir1, dir2 etc.

What would probably be the easiest to follow such case would be to be able to pass a regex in those parameters, in my case it would lead to include "*/test" and if a user want to only include 2 directories, he would be able to pass "dir1|dir2" also. In this case, only passed directories should appear in the GUI part including the source coverage.

I would be able to help, but I am not sure where to start, it seems core/traceability_index_builder.py is where modifications should be done, but I did not dig deep enough.

**Comment by stanislaw** [comment]
I could not find enough time to advance with the work on the filters. Nevertheless, I could create a branch with some initial code that goes into the direction: https://github.com/strictdoc-project/strictdoc/pull/1170.

The tricky part that I see along the way of implementing it is how to implement a consistent set of filters. I am thinking of modeling how Git filters things in the `.gitignore` file.

For example, I am thinking of supporting the wildcards `*` and `**`.

Open questions:

Which kind of filters should be supported? I could think of:

```toml
[project]

include_source_paths = [
  "src1/*",  # only files in the src1 directory itself
  "src1/**",  # all files in the src1 directory, any level of nesting
  "src",  # should 'src' behave like 'src/'?
  "src1/*.py"
]

features = [
  "REQUIREMENT_TO_SOURCE_TRACEABILITY"
]
```

Which other combinations should the filter support? Note that it would be great to use the same implementation of a filter to also include/exclude `*.sdoc` files in certain directories.

**Comment by Minipada** [comment]
My current case is "*/test/**" so it should work with how you described it.

I like the gitignore idea, because it is easy but it can be a pain in some cases.
There may be a case where users would want regex, for example to match any string except a certain string. And if this is the case, with the current implementation, we would need to have a line for each match and update it constantly when we add one, which is not practical...
