### ISSUE TITLE
Feature onmouseclick section or requirement edit 

### ISSUE THREAD

**Issue by elfman2** [strictdoc-project/strictdoc#1176]
On the web client, to edit a section or a requirement, on mouse click event would be more convenient than the edit button.

**Comment by stanislaw** [comment]
Hey @elfman2, I am discussing this with @mettta now. How do you see this to work in terms of the clickable area? Where exactly do you want to click to enter the edit mode?

We see a small contradiction with the fact that you may also want to double-click to select the parts of text in requirement or section text fields. Supporting both features could cause unexpected behavior to either entering edit mode or entering text selection mode.

<img width="638" alt="Bildschirmfoto 2023-10-20 um 22 00 41" src="https://github.com/strictdoc-project/strictdoc/assets/452547/1b2aaddf-957c-400e-bea0-9c3cf009b4db">

**Comment by elfman2** [comment]
Or the other way around:
-Double click to edit
-Click to select
?

**Comment by stanislaw** [comment]
> Or the other way around:
> -Double click to edit
> -Click to select

This would be a non-standard browser behavior then.

I would like to close this ticket as not clarified enough. Feel free to reopen if you have a clear idea. We believe that clicking on an edit button is a decent solution for now.
