### ISSUE TITLE
Unable to reference .cc files

### ISSUE THREAD

**Issue by ThomasHovey** [strictdoc-project/strictdoc#1199]
We have a large project using .cc extention for our C++ files as per the Google Coding standard. 

Using the strictdox-examples repo I can reference a .cpp file but when I rename the same file to a .cc file I get the following error:

```
WARNING:  Current configuration will not reload as not all conditions are met, please refer to documentation.
Step 'Parse SDoc project tree' start.
Step 'Find and read SDoc files' start.
Reading SDOC: example_01.sdoc ............................... 0.05s
Reading SDOC: example_02.sdoc ............................... 0.07s
Reading SDOC: example_03.sdoc ............................... 0.04s
Reading SDOC: example_04.sdoc ............................... 0.04s
Reading SDOC: example_05.sdoc ............................... 0.09s
Reading SDOC: example_06.sdoc ............................... 0.04s
Reading SDOC: example_07.sdoc ............................... 0.04s
Reading SDOC: example_08.sdoc ............................... 0.04s
Step 'Find and read SDoc files' took: 0.41 sec.
Step 'Build traceability graph' start.
Step 'Build traceability graph' took: 0.01 sec.
error: Requirement REQ-003 references a file that does not exist: examples/example_source_files/file2.cc.
```

I am using the latest pip installed version 0.0.42.

I also cloned the repo and tried to modify this myself by changing the SourceFileType in strictdoc/core/finders/source_files_finders.py to include .cc options however this did not work. I could not see anywhere else in the repo that filters by file type. 

```
class SourceFileType(Enum):
    PYTHON = [".py"]
    C = [".c"]
    CPP = [".cpp", ".cc"]
    TEX = [".tex"]
    # Is there an idiomatic file extension for Jinja templates?
    # https://stackoverflow.com/questions/29590931/is-there-an-idiomatic-file-extension-for-jinja-templates  # noqa: #501
    JINJA = [".jinja", ".jinja2", ".j2", ".html.jinja"]

    @classmethod
    def create_from_path(cls, path_to_file: str) -> "SourceFileType":
        assert os.path.isfile(path_to_file), path_to_file
        if path_to_file.endswith(".py"):
            return cls.PYTHON
        if path_to_file.endswith(".c"):
            return cls.C
        for enum_value in SourceFileType.CPP.value:
          if path_to_file.endswith(enum_value):
              return cls.CPP
        if path_to_file.endswith(".tex"):
            return cls.TEX
        for enum_value in SourceFileType.JINJA.value:
            if path_to_file.endswith(enum_value):
                return cls.JINJA
        raise NotImplementedError(path_to_file)
        
```

This can be replicated by simply renaming one of the test files in the example repo to use .cc and .cpp file extentions. It would be ideal to have this tool support .cc extentions as the google standard is widely used. There are also a few other cpp extentions that are common that would be worth supporting.

**Comment by stanislaw** [comment]
Thanks for reporting this, and I am glad that you are evaluating this still experimental feature!

I cannot tell from the top of my head what's the reason but I will take a closer look this evening.

**Comment by ThomasHovey** [comment]
Thanks @stanislaw. That works well. 

I am not sure what I did wrong - I am not that familiar with python and just tried running the modified application by calling python3 strictdoc/cli/main.py. 

Other common cpp extentions that I am familiar with are: ".cc" ".C" ".cxx" ".c++"

**Comment by stanislaw** [comment]
> Thanks @stanislaw. That works well.
> 
> I am not sure what I did wrong - I am not that familiar with python and just tried running the modified application by calling python3 strictdoc/cli/main.py.

With a clear mind in the morning 😄 , I think you could have hit the undefined behavior of imports because you probably had not uninstalled the `strictdoc` Pip package from your system. When a Pip package is installed, even if you are running a script from a repo, it usually messes up the imports by taking them from the Pip package `PATH`s. IIRC, some imports can be still taken from cloned code. This is one of the reasons why all StrictDoc's development tasks are wrapped into Tox calls that create isolated Python environments or I need to make sure that I remove the Pip version before running anything else with `python strictdoc/...`.

> Other common cpp extentions that I am familiar with are: ".cc" ".C" ".cxx" ".c++"

I will add them to the integration test from the same changeset within this weekend. By the way, I was also expecting that you would bring some other header files examples. I guess, we need to add something like .hpp or .hxx?
