### ISSUE TITLE
multi-line fields not preserving whitepace in all formats (rst:yes, html:no)

### ISSUE THREAD

**Issue by BenGardiner** [strictdoc-project/strictdoc#1212]
our webpages built with strictdoc at https://github.com/nmfta-repo/vcr-experiment : https://nmfta-repo.github.io/vcr-experiment/ have RST formatting in the PUB_REFs fields.

Recently we noticed that the RST code blocks for ASCII diagrams weren't rendering anymore. But they _do_ render in a RST->TEX->PDF workflow
![image](https://github.com/strictdoc-project/strictdoc/assets/243321/d2f3e276-9619-4874-a1dc-0b5f5c723857)

(I can show this side by side because we now have PDF generation ready in a PR here https://github.com/nmfta-repo/vcr-experiment/pull/53)

But it's not just limited to those diagrams. It seems that all the RST formatting for bullets and quote blocks are also broken:
![image](https://github.com/strictdoc-project/strictdoc/assets/243321/ed443526-e00d-407a-ac27-edbb0dd6f2d4)

(NB: this is perhaps related to #1210 not sure)

I do not have any ideas where to start tracking down this issue in strictdoc codebase.

**Comment by stanislaw** [comment]
Could you give me a minimal chunk of RST code that reproduces this?

**Comment by BenGardiner** [comment]
The first screenshot above is from this:
```
VERIFICATION: >>>
Inspection of vendor documentation to confirm that device's implementation follows the rules for CAN arbitration ID priority and the prevention of priority inversion.

AND

Inspection of vendor report detailing the use of a test environment that simulates a bidirectional UND <-> TND operation, with different arbitration ID priorities. Where, with the test environment set up, a CAN analyzer or other monitoring tool was used to observe the device's scheduling of egress frames and verify that it followed the correct arbitration ID priority: that higher-priority frames are always transmitted before lower-priority frames. The test methodoly described in the report should be comparable to the following:

::


       +---------+                                      +---------+
       |         |                                      |         |
       | Monitor |                                      | Monitor |
       |         |                                      |         |
       +---+-----+          +--------------+            +---+-----+
    +-+    |        UND     |              |    TND         |       +-+
    |+|    |                |   Security   |                |       |+|
    |++----+----------+-----+    Gateway   +-------+--------+-------++|
    |+|               |     |              |       |                |+|
    +-+               |     +--------------+       |                +-+
                      |                            |
                      |                            |
                      |        +--------+          |
                      |        |        |          |
                      +--------+ Tester +----------+
                               |        |
                               +--------+

Figure 1
[...]
```

the second is from:
```
PUB_REFS: >>>

* https://www.autosar.org/fileadmin/user_upload/standards/foundation/19-11/AUTOSAR_TR_SecureHardwareExtensions.pdf for an example of a suitable HSM (the SHE+ HSM).

    Access control mechanisms to restrict access to critical ECUs, critical modes of every ECU (diagnostic mode), and their data.

    -- SAE J3061: Appendix F - VEHICLE LEVEL CONSIDERATIONS, Security Mechanisms, b.

    Mechanisms that effectively secure maintenance operations, including both diagnostic procedures and update procedures.

    -- SAE J3061: Appendix F - VEHICLE LEVEL CONSIDERATIONS, Security Mechanisms, g.
<<<
```

**Comment by stanislaw** [comment]
<img width="785" alt="Bildschirmfoto 2023-07-05 um 22 40 36" src="https://github.com/strictdoc-project/strictdoc/assets/452547/07d02158-3159-457a-a0ca-7771470b1693">

I am seeing it correctly in the FREETEXT. It looks like I need to switch to your tree to check the custom fields.

**Comment by stanislaw** [comment]
How do you create this ASCII btw? A tool or by hand?

**Comment by BenGardiner** [comment]
hmmm yes that's correct. in all cases the rendering problems were in custom grammar fields

> How do you create this ASCII btw? A tool or by hand?
 the amazing https://asciiflow.com/#/ !

**Comment by stanislaw** [comment]
A non-custom multiline field works for me. Checking further.

**Comment by stanislaw** [comment]
Ok, I have it now. A custom field is not working.

**Comment by stanislaw** [comment]
I am surprised to see that we actually missed to render all multiline fields to RST 🤔 

The fix is on the way: https://github.com/strictdoc-project/strictdoc/pull/1214.

**Comment by BenGardiner** [comment]
Thank you!
