### ISSUE TITLE
Arrow is missing for the last requirement of a document in the requirements coverage page

### ISSUE THREAD

**Issue by fniu** [strictdoc-project/strictdoc#1298]
Hi there,

The arrow would be missing only if the parent requirement is the last requirement of the current document, and neither the parent nor child requirements have a title.

Also, it would be good to enlarge the box of a requirement when its title is missing so the positions of the arrows are in the right places.

See the screenshot below. The arrow from SUB_REQ_002 to REQ-002 is missing.
![143426](https://github.com/strictdoc-project/strictdoc/assets/1160165/e713b96a-00fb-4a86-a5bb-40366fe90671)

**Comment by stanislaw** [comment]
Hi @fniu, thanks for reporting this.

We are aware of this issue, and it is tracked here: https://github.com/strictdoc-project/strictdoc/issues/1111 but we will give it a bump in our priorities. Just too many other tasks happening in parallel.

**Comment by stanislaw** [comment]
No longer actual due to https://github.com/strictdoc-project/strictdoc/pull/1531.
