### ISSUE TITLE
relative source file path ../src no supported

### ISSUE THREAD

**Issue by elfman2** [strictdoc-project/strictdoc#1306]
in strictdoc.toml
include_source_paths = [
   "../src/**"
]

strictdoc server
error: strictdoc.toml: 'include_source_paths': Path mask must start with an alphanumeric character or a wildcard symbol '*'. Provided string: '../src/**'.

**Comment by stanislaw** [comment]
Thanks for reporting this as well.

Before I will start introducing the relative paths support which is always connected to all sorts of edge cases, could you check if the `--config` option could allow you to specify the StrictDoc configuration file one level above your docs folder? Then you would not need to go up with your relative path pointing.

The `--config` option is available in the nightly version.

**Comment by elfman2** [comment]
Hi Stanislas,
The --config workaround is ok

Thks!

**Comment by stanislaw** [comment]
Thanks for coming back about this one. I will close it then for the time being.
