### ISSUE TITLE
Requirements are missing sdoc-anchor

### ISSUE THREAD

**Issue by fniu** [strictdoc-project/strictdoc#1363]
With the latest version 0.0.45 (which I happended to upgrade to and tried), it seems to me that the `sdoc-anchor` elements are missing for requirements. Therefore the reference links and the TOC don't work any more.

**Comment by stanislaw** [comment]
Thanks a lot for reporting this! We know exactly what happened and are working on a fix now.

**Comment by stanislaw** [comment]
The new 0.0.46 has been released. Let me know if it works, and thanks again for your superfast report!
