### ISSUE TITLE
Export with grammar filter

### ISSUE THREAD

**Issue by villanella** [strictdoc-project/strictdoc#1374]
I have a large documents with requirements. Each requirement or freetext block has some default or custom grammar field values. For example, "Status"="Draft" or "Story"="ABC-123" (issue ID in Jira).
I want to export/publish not the whole documents, but only items having the field with concrete value.

Example of usage:
`strictdoc export <input_paths> --output-dir <output_dir> --filter <field>=<value>`
`strictdoc export docs --output-dir output --filter UID=ABC-123`

Expected result: exported items only with defined grammar field values.

**Comment by villanella** [comment]
> @villanella and everyone who is interested in this feature. Due to the introduction of a [query engine](https://github.com/strictdoc-project/strictdoc/pulls?q=is%3Apr+is%3Aclosed+query) and the [search screen](https://github.com/strictdoc-project/strictdoc/issues?q=search), we are now very close to implementing this kind of `grammar filters`, also from the command-line.
> 
> The only question which seems to be undecided is how to deal with sections. What if a section contains of all the requirements that are filtered out? Does this section have to be excluded as well from the document automatically?
> 
> Note that there is a similar ticket here: #601.


Section having UID or some custom tag for filtering, I think, shouldn't be excluded, because it keeps the important information about nested structure of its requirements. It can be useful, for example, when implementation/configuration details are nested into functional requirements as included section. Or when requirements are combined into the section corresponding to the use-case or user story.
Section can have some additional information in Freetext block that should be included into the export.
If user doesn't want to include section, he doesn't use the UID or tag in the section. So Strictdoc should export not only requirements, but all items, that have been filtered.

**Comment by stanislaw** [comment]
A new version has been released today. See the new section called Release Notes: https://strictdoc.readthedocs.io/en/latest/strictdoc_04_release_notes.html#id1.

One of the new features is "Search and filtering", https://strictdoc.readthedocs.io/en/stable/strictdoc_01_user_guide.html#search-and-filtering

Let me know if this gives you what you were looking for. Any feedback is appreciated.

**Comment by stanislaw** [comment]
To improve the visibility into current work, I prefer to close this ticket because at least good 80%+ of the feature are already released. If you will have any specific feedback, please open dedicated focused tickets.
