### ISSUE TITLE
Update strictdoc.tmLanguage

### ISSUE THREAD

**Issue by mettta** [strictdoc-project/strictdoc#1589]
![image](https://github.com/strictdoc-project/strictdoc/assets/490084/c00a7701-51e9-416d-9e66-e0b52da1c562)

https://github.com/strictdoc-project/strictdoc.tmLanguage

**Comment by stanislaw** [comment]
Closed with https://github.com/strictdoc-project/strictdoc.tmLanguage/pull/11, https://github.com/strictdoc-project/strictdoc.tmLanguage/pull/10, https://github.com/strictdoc-project/strictdoc.tmLanguage/pull/8.
