### ISSUE TITLE
Will not process sdoc files in --output-dir

### ISSUE THREAD

**Issue by KlfJoat** [strictdoc-project/strictdoc#1620]
Per `strictdoc about`, I'm running `Version: 0.0.48`.

It seems that if an `.sdoc` file is in the same directory as `--output-dir`, StrictDoc will not process that `.sdoc` file.

Given the following directory structure...

```shell
tree -L 2 -P '*.sdoc' -P 'strictdoc.toml' --prune -n --charset=ascii
```

```text
.
|-- qux
|   `-- foo.sdoc
|-- zzy
|   `-- bar.sdoc
`-- strictdoc.toml
```

And this `strictdoc.toml` file...

```toml
[project]
title = "myproj"

include_doc_paths = [
  "zzy/*.sdoc",
  "qux/*.sdoc"
]
```

When running the following `strictdoc` commands, I get the associated output below.

```shell
strictdoc export --output-dir=zzy .
```
```text
Parallelization: Enabled                          
Step 'Parse SDoc project tree' start.                                                               
Step 'Find and read SDoc files' start.                                                              
Reading SDOC: foo.sdoc ...................................... 0.05s
Step 'Find and read SDoc files' took: 0.06 sec.
Step 'Build traceability graph' start.
Step 'Build traceability graph' took: 0.01 sec.                                                     
Step 'Parse SDoc project tree' took: 0.07 sec.
Step 'Export SDoc' start.            
Copying StrictDoc's assets: 37 files (37 files skipped as non-modified).
Published: foo .............................................. 0.13s
Export completed. Documentation tree can be found at:              
/home/klfjoat/src/myproj/zzy/html      
Step 'Export SDoc' took: 0.18 sec.
```

:arrow_up: As you can see, when `--output-dir=zzy`, the `bar.sdoc` file in that dir is not read in. :arrow_up:

```shell
$ strictdoc export --output-dir=qux .
```
```text
Parallelization: Enabled                          
Step 'Parse SDoc project tree' start.
Step 'Find and read SDoc files' start.                                                              
Reading SDOC: bar.sdoc ............................. 0.00s
Step 'Find and read SDoc files' took: 0.01 sec.                                                     
Step 'Build traceability graph' start.                                                              
Step 'Build traceability graph' took: 0.01 sec.
Step 'Parse SDoc project tree' took: 0.02 sec.
Step 'Export SDoc' start.                         
Copying StrictDoc's assets: 37 files (37 files skipped as non-modified).
Published: bar ....................... 0.11s
Export completed. Documentation tree can be found at:
/home/klfjoat/src/myproj/qux/html
Step 'Export SDoc' took: 0.16 sec.
```

:arrow_up: When `--output-dir=qux`, the `foo.sdoc` file in THAT dir is not read in. :arrow_up:

```shell
$ strictdoc export .
```
```text
Parallelization: Enabled
Step 'Parse SDoc project tree' start.
Step 'Find and read SDoc files' start.
Reading SDOC: bar.sdoc ............................. 0.00s
Reading SDOC: foo.sdoc ...................................... 0.05s
Step 'Find and read SDoc files' took: 0.06 sec.
Step 'Build traceability graph' start.
Step 'Build traceability graph' took: 0.01 sec.
Step 'Parse SDoc project tree' took: 0.07 sec.
Step 'Export SDoc' start.
Copying StrictDoc's assets: 37 files.
Published: bar ....................... 0.11s
Published: foo .............................................. 0.13s
Export completed. Documentation tree can be found at:
/home/klfjoat/src/myproj/output/html
Step 'Export SDoc' took: 0.18 sec.
```

:arrow_up: And when there is no `--output-dir` or it's been set to a different location, both files are read in. :arrow_up:

I expected to be able to generate the output in a subdir of my documentation dir, then move it to its final location (since I can't get rid of the `html` dir, I have to move it anyway).

**Comment by stanislaw** [comment]
The behavior you are reporting is as expected. This is how it is implemented in the code, see `ignored_dirs`:

![image](https://github.com/strictdoc-project/strictdoc/assets/452547/f8a1693f-8dfc-4db3-9c7b-34b962308adb)


The idea was to exclude the output folder itself because if the reqs-to-source traceability is enabled, StrictDoc will start finding source files from the output folder which is not what you want in a general case. Removing the output dir from the ignored folders would mean that 100% of users have to exclude the `output/` in their configs all the time.

**Comment by stanislaw** [comment]
From your folder names `zzy` and `qux` it is not clear which documentation pipeline you are setting up but I guess it should be possible for you to implement a workflow which does not require StrictDoc to change this behavior. Let me know if you believe otherwise.

**Comment by KlfJoat** [comment]
So it sounds like this behavior is by design.  Might I suggest including this behavior in the User Guide and/or in the output of StrictDoc when it detects the condition? It was quite confusing to try to figure out what stopped working.

It is absolutely possible for me to change my workflow to avoid this. I just didn't know what was going on because there was no mention of it.

**Comment by KlfJoat** [comment]
FYI, I'm fine with closing this issue, I'd just appreciate it if the decision was documented in the User Guide somewhere.

**Comment by stanislaw** [comment]
It is a good question where this should go. As a newcomer, where would you like to see it?

**Comment by KlfJoat** [comment]
IMO, having it in the User Guide under "Export formats" is a good location.

But also, I'm a fan of programs telling me if I do something wrong. So instead of some kind of silent ignoring, I'd like to see something sent to stderr like ".sdoc files found in output dir zzy. They will be ignored."

**Comment by stanislaw** [comment]
> IMO, having it in the User Guide under "Export formats" is a good location.

I have added a note in the Export formats just now, see https://github.com/strictdoc-project/strictdoc/pull/1673.

> But also, I'm a fan of programs telling me if I do something wrong. So instead of some kind of silent ignoring, I'd like to see something sent to stderr like ".sdoc files found in output dir zzy. They will be ignored."

It is a nice suggestion but I prefer to keep this out of scope for now. I will keep this issue somewhere in the back of my mind, and maybe at some point something like this will be implemented. Closing for now.
