### ISSUE TITLE
Excel export: export multiple documents with relations between them, document the common commands

### ISSUE THREAD

**Issue by Dynteq** [strictdoc-project/strictdoc#1639]
Hi all,
Congrats on a very sleek tool, StrictDoc is exactly what we need. Small Fast and with a readable file format.

Using: Strictdoc 0.0.47 on Windows

I's taken me forever to figure out how to export a multi file project to Excel. I would like to add a more comprehensive example with some explanation like:

`strictdoc export --formats=excel --fields=UID,STATUS,TITLE,STATEMENT,RATIONALE,MYFIELD,COMMENT --output-dir=output .`

Initially the fields were unclear but the final . really had me puzzled.

The PARENT field can only be used on documents that only contain internal relations. Using it on the whole project like above results in a KeyError

Background:
I've setup a project with three .sdoc files. One main document for the system requirements and 2 for separate subsystems. In these subsystem files I reference requirements in the main document. This works fine in the web interface, complete with clickable links in both directions.
The idea is that both sub-contractors will manage their own file and we control the main file form the project organization.

I'd really like to help, but I have no formal education as a programmer, so I might need some guidance.

**Comment by stanislaw** [comment]
Hey @Dynteq, thanks for reporting the KeyError and giving your feedback.

I have fixed the KeyError and added some documentation here: https://github.com/strictdoc-project/strictdoc/pull/1643. Now instead of a KeyError, if a relation points to another document, it is simply printed as text, not as an Excel internal link.

To try the new modification, you have to install the nightly version of StrictDoc using `pip install strictdoc --pre`. This will give you the latest `0.0.49a4` version which has this fix.

Let me know if it works. I am closing this issue for now. If something else will not work, please open new issues accordingly.

**Comment by Dynteq** [comment]
Hi Stanislav,
Excellent! Thank you. (please excuse the pun)
That works fine. As a workaround I did something similar, replacing the write_url with a plain write.


Met vriendelijke groet / With best regards,

Martijn Smit
lead engineer
+31 (0)6 43 69 85 56



[cid:Logo_Dynteq_mail_ddb69547-68b9-4197-a463-2a947c97291c.png]<http://www.dynteq.nl>


Vliegveldstraat 100, B514
7524 PK ENSCHEDE        dynteq.nl<http://www.dynteq.nl/>
+31 (0)53 436 73 33     [cid:Logo_Dynteq_mail-linkedin_f57e7d3f-0431-4d67-bbd4-007aa8f58723.png] <https://www.linkedin.com/company/dynteq>   [cid:Logo_Dynteq_mail-facebook_76ef1e0b-08ac-4339-9753-552b153d2adf.png] <https://www.facebook.com/dynteq>   [cid:Logo_Dynteq_mail-twitter_c2b1324c-4f9b-4184-b1af-121d02cbd729.png] <https://www.twitter.com/dynteq>   [cid:Logo_Dynteq_mail-instagram_fa06e350-a983-4f3f-9f9b-48608fca6fef.png] <https://www.instagram.com/dynteq>   [cid:Logo_Dynteq_mail-youtube_e4088713-77de-4217-aa0d-8ab1b415c83c.png] <https://www.youtube.com/c/DynteqNlEnschede%20>


De informatie verzonden met dit e-mailbericht is uitsluitend bestemd voor de geadresseerde(n). Openbaarmaking, vermenigvuldiging, verspreiding en/of verstrekking aan derden is niet toegestaan. Indien u deze e-mail abusievelijk hebt ontvangen, verzoeken wij u hem te verwijderen en de afzender hiervan op de hoogte te stellen. De vertrouwelijkheid van dit bericht is niet gewaarborgd. Dynteq sluit iedere aansprakelijkheid uit die voortvloeit uit elektronische verzending.

The information contained in this communication is intended solely for the use of the individual or entity to whom it is addressed, and others authorized to received it. You are hereby notified that any disclosure, copying, distribution or action in relation to the contents of this information is strictly prohibited. If you are not the intended recipient, please delete this message and any attachments and advise the sender by return e-mail. The confidentiality of this message is not warranted. Dynteq rules out any and every liability resulting from this or any other electronic transmission.
Van: Stanislav Pankevich ***@***.***>
Verzonden: zondag 11 februari 2024 13:46
Aan: strictdoc-project/strictdoc ***@***.***>
CC: Martijn Smit ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [strictdoc-project/strictdoc] Excel export: export multiple documents with relations between them, document the common commands (Issue #1639)


Hey @Dynteq<https://github.com/Dynteq>, thanks for reporting the KeyError and giving your feedback.

I have fixed the KeyError and added some documentation here: #1643<https://github.com/strictdoc-project/strictdoc/pull/1643>. Now instead of a KeyError, if a relation points to another document, it is simply printed as text, not as an Excel internal link.

To try the new modification, you have to install the nightly version of StrictDoc using pip install strictdoc --pre. This will give you the latest 0.0.49a4 version which has this fix.

Let me know if it works. I am closing this issue for now. If something else will not work, please open new issues accordingly.
