### ISSUE TITLE
0.0.53 GUI does not maintain in fragment file the grammar via IMPORT_FROM_FILE

### ISSUE THREAD

**Issue by gregshue** [strictdoc-project/strictdoc#1764]
When I used the GUI of Strictdoc 0.0.53 to add successive requirements in an sdoc fragment file the updated file now had the grammar inline instead of IMPORT_FROM_FILE. I had to manually replace the inline grammar with the reference before I could commit the file.

- My environment was Ubuntu 22.04 and interfacing through Firefox. 
- I experienced this while creating [this](https://github.com/zephyrproject-rtos/reqmgmt/pull/29) PR for Zephyr Project.

**Comment by stanislaw** [comment]
In the just-released `0.0.54a` (installable with `pip install strictdoc --pre`), this should be working now.
