### ISSUE TITLE
0.0.53 GUI does not support adding section or requirement to "empty" fragment file.

### ISSUE THREAD

**Issue by gregshue** [strictdoc-project/strictdoc#1765]
In Strictdoc 0.0.53 the GUI did not give me the option to add a section or requirement into a fragment file that contains only the following:

1. DOCUMENT content, and
2. GRAMMAR content (via IMPORT_FROM_FILE), and
3. FREETEXT content.

Once I added the first item through a text editor I was able to add further items through the GUI.

- I found this while on Ubuntu 22.04 and interfacing through Firefox. 
- I found this while working on [this](https://github.com/zephyrproject-rtos/reqmgmt/pull/29) PR for the Zephyr Project.

**Comment by stanislaw** [comment]
In the just-released `0.0.54a` (installable with `pip install strictdoc --pre`), this should be working now. The UI automated tests are written to support this but we haven't tested enough this and other related cases manually. Let us know if it works for you.
