### ISSUE TITLE
Extend GUI to support adding FREETEXT blocks

### ISSUE THREAD

**Issue by gregshue** [strictdoc-project/strictdoc#1766]
I would like the GUI to support adding/editing FREETEXT blocks in the same way it supports adding sections and items. It would be even better if the default content for FREETEXT blocks was "TBD".

**Comment by stanislaw** [comment]
Thanks for reporting this. Adding FREETEXT blocks using UI is on the roadmap and tracked here: https://github.com/strictdoc-project/strictdoc/issues/1518.

@mettta and I were planning to implement this still in 2024-Q2.

**Comment by stanislaw** [comment]
Closed with the release: https://github.com/strictdoc-project/strictdoc/releases/tag/0.0.57. Please see the release notes.
