### ISSUE TITLE
Broken command manage auto-uid / Import sgra content into file when using manage auto uid

### ISSUE THREAD

**Issue by simhein** [strictdoc-project/strictdoc#1804]
I try to address two issues here, I discovered in strictDoc,
Please let me know if I should separate them into own github issues

1.  Broken command `strictdoc manage auto-uid .` after changing to version 0.0.54 and 0.0.55
Executing the command in that two versions leads to following AttributError:
```
  File "/home/hsim/.local/bin/strictdoc", line 8, in <module>
    sys.exit(main())
  File "/home/hsim/.local/lib/python3.10/site-packages/strictdoc/cli/main.py", line 195, in main
    raise exc
  File "/home/hsim/.local/lib/python3.10/site-packages/strictdoc/cli/main.py", line 190, in main
    _main(parallelizer)
  File "/home/hsim/.local/lib/python3.10/site-packages/strictdoc/cli/main.py", line 143, in _main
    ManageAutoUIDCommand.execute(
  File "/home/hsim/.local/lib/python3.10/site-packages/strictdoc/commands/manage_autouid_command.py", line 72, in execute
    document_content = SDWriter().write(document)
  File "/home/hsim/.local/lib/python3.10/site-packages/strictdoc/backend/sdoc/writer.py", line 68, in write
    document_output, _ = self.write_with_fragments(document)
  File "/home/hsim/.local/lib/python3.10/site-packages/strictdoc/backend/sdoc/writer.py", line 253, in write_with_fragments
    output += self._print_node(document, document, document_iterator)
  File "/home/hsim/.local/lib/python3.10/site-packages/strictdoc/backend/sdoc/writer.py", line 274, in _print_node
    if not node_.ng_whitelisted:
AttributeError: 'DocumentFromFile' object has no attribute 'ng_whitelisted'
```

A short node, which might help: The command is used with DOCUMENT_FROM_FILE imports.

2.  Grammar File (.sgra) is imported into File when using `strictdoc manage auto-uid .`
When using a grammar file and than executing the command `strictdoc manage auto-uid .` the content of the grammar file is imported into the file where the UIDs are set.

**Comment by stanislaw** [comment]
@simhein thanks a lot for reporting this. I am most certain that the issues like these have been fixed quite some time ago during the migration from `FRAGMENT_FROM_FILE` to `DOCUMENT_FROM_FILE`.

The best guess is that you may be hitting an outdated StrictDoc cache which is stored on your system at `$TMPDIR/strictdoc_cache`. Could you remove that folder and try your reproducing commands again?

(I am working on improving the error messages, so that it would be clear from the error message itself which reasons can hide behind the stack traces. For now, it is great that you proactively reported this issue right away.)

**Comment by simhein** [comment]
> @simhein thanks a lot for reporting this. I am most certain that the issues like these have been fixed quite some time ago during the migration from `FRAGMENT_FROM_FILE` to `DOCUMENT_FROM_FILE`.
> 
> The best guess is that you may be hitting an outdated StrictDoc cache which is stored on your system at `$TMPDIR/strictdoc_cache`. Could you remove that folder and try your reproducing commands again?
> 
> (I am working on improving the error messages, so that it would be clear from the error message itself which reasons can hide behind the stack traces. For now, it is great that you proactively reported this issue right away.)

Hey @stanislaw deliting the  `$TMPDIR/strictdoc_cache` folder did the trick and it is working as intended.
Both issues are resolved and I will close this issue

**Comment by stanislaw** [comment]
Perfect! Every feature introduced has a trail of issues associated with it: there are a few more work items related to the composable documents feature, and I am working on them, one at a time. https://github.com/strictdoc-project/strictdoc/issues/1698
