### ISSUE TITLE
[bug] literal blocks and code blocks crash the server

### ISSUE THREAD

**Issue by podhrmic** [strictdoc-project/strictdoc#1836]
How to reproduce?

Add either *literal blocks* `::` or `.. code-block:: c` anywhere in your requirements document.

Result?
```
error: problems when converting RST to HTML:
...
# Very long trace
# Server crashes
```

Perhaps neither literal blocks or code blocks are supported?

**Comment by stanislaw** [comment]
It is a good catch. What is known to be supported:

- `.. code-block::`
- `.. code-block:: text`
- `.. code-block:: bash`
- `.. code-block:: yaml`

We will investigate what happens if `c` is passed.

Thanks for reporting this.

**Comment by podhrmic** [comment]
Thanks for the quick reply!

Upon further inspection, *this* is the minimal requirement that triggers the error:

```
[REQUIREMENT]
MID: 38dbcc6d1cc042749c550ff7394513db
UID: TA2-REQ-9
TITLE: Nested types
STATEMENT: >>>
Lorem Ipsum.
<<<
RATIONALE: >>>
Lorem Ipsum.

.. code-block:: text
  struct S {
  T1 S1;
  T2 *S2;
  T3 S3[];
  }

Lorem ipsum.
<<<
```

Leads to `error: problems when converting RST to HTML:`

**Comment by podhrmic** [comment]
Silly mistake - thank you for pointing it out so quickly!
