### ISSUE TITLE
Cannot find the Search screen in the web interface

### ISSUE THREAD

**Issue by Dynteq** [strictdoc-project/strictdoc#1988]
Updated to 0.2.0 yesterday.

In the documentation it says: 
"The web interface includes the Search screen, designed for conducting queries against a document tree."
But I can't find it. Maybe I'm looking in the wrong place, or something went wrong with my update, or it could be an error in the documentation or a bug?

The tags at the top of the table view are visible. I was hoping to filter according to those tags. 

![image](https://github.com/user-attachments/assets/8048e228-09aa-46b5-80f6-f62c87822757)

I like the lightweight program a lot so far, keep it up.

Cheers,

**Comment by stanislaw** [comment]
Thanks for reporting this!

It looks like we missed to document that this is a feature behind a feature toggle. You need to include it in the TOML config, see here for an example: https://github.com/strictdoc-project/strictdoc/blob/main/strictdoc.toml#L12.

**Comment by Dynteq** [comment]
Thank you,

Adding "SEARCH", under features in the .toml configuration file solved it.

I successfully filtered on TAGS with the following query:
`(node.is_requirement and "All" in node["TAGS"])`
Where "All" was the tag I was looking for.

For mee this is closed, but it may need to be added to the documentation.

Cheers,

**Comment by stanislaw** [comment]
:partying_face: 

Yes, let's not close it before I have this documented.

**Comment by stanislaw** [comment]
I have documented it here: https://github.com/strictdoc-project/strictdoc/pull/1989. The https://strictdoc.readthedocs.io/en/latest/strictdoc_01_user_guide.html#search-and-filtering.
