### ISSUE TITLE
HTML anchors are not working

### ISSUE THREAD

**Issue by stumpyfr** [strictdoc-project/strictdoc#268]
When generating the HTML output, the anchor links to navigate between refs are not working:

<img width="995" alt="Screenshot 2020-12-29 at 11 38 45" src="https://user-images.githubusercontent.com/1849743/103287124-fdd50f00-49e1-11eb-8b7b-46f425ba7257.png">

Looks like missing the anchor after the `#` in the link (see the bottom part of the screenshot)

**Comment by stanislaw** [comment]
@stumpyfr I believe that links are working now. At least they are consistenly on my *.sdoc set 😃

**Comment by stumpyfr** [comment]
confirmed,
