### ISSUE TITLE
Custom fields usage

### ISSUE THREAD

**Issue by stumpyfr** [strictdoc-project/strictdoc#269]
Hi,

As discussed in #258, the need for custom fields is "important", top of my mind:

- Owner
- Priority

Use case: I am working on a very large project with multiple companies involved, I need to clearly define the owner for each requirement and be able to track/order priority.

I can see two options:

1. Allowing custom fields, after the "standard one"
 1.1 would allow to use them easily in export, for example when excel columns would be configurable
2.  allowing more flexible tag, ex: `owner=C1, Foo, Bar, priority=P1`

Open for discussion!

**Comment by stanislaw** [comment]
The initial support of the `special fields` has landed. There is no documentation yet, but you can see the example here: https://github.com/strictdoc-project/strictdoc/pull/280/files#diff-26d73653a4857faf0f1186aba52ec529d929de48039840844e64cb672e7fafb7R3.

I have been thinking about this feature for a few months and considered a number of trade-offs that influenced the current grammar and the implementation. The idea is to declare special fields on a document level to provide a structure for writing them on a requirement level: this includes a type system and the necessary validation: types could be 'String', 'Enum', 'Int', 'Boolean', the validation rules could be "Required: Yes/No", uniqueness checks, regex checks, etc. For now, all special fields can only be of `String` type. Later, more types and corresponding validations can be introduced.

Just for your interest, here is the implementing PR: https://github.com/strictdoc-project/strictdoc/pull/277.

**Comment by stumpyfr** [comment]
awesome.
Tested and working well.

How can we access them from the code? The next move for me would be to be able to export them into Excel, so maybe first need to work on the fact we need to be able to provide the list of columns we want to export.

will check tomorrow if I have time to work on iit.

**Comment by stanislaw** [comment]
I think this can be closed now. All future work will be handled in separate tickets.
