### ISSUE TITLE
export/excel: make fields configurable

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#272]
[Current Excel generation code](https://github.com/strictdoc-project/strictdoc/blob/30087b391992166c1fa66c627214c42bf3a87e44/strictdoc/export/excel/excel_generator.py#L22) does not export all fields.

It should be possible to specify which fields should be exported to Excel.

One possible solution would be to add the `--fields` parameter:

`strictdoc export --formats=excel --fields=uid,title,statement,rationale`

Another option would be to introduce a configuration file `.strictdoc.toml` with the `[excel]` configuration section.

**Comment by stumpyfr** [comment]
handled in #282 

the configuration file would be nice, still, we need to be able to override by command line as we have now.
