### ISSUE TITLE
Installation problems on Ubuntu 20.04

### ISSUE THREAD

**Issue by RobertoBagnara** [strictdoc-project/strictdoc#326]
I have followed the instructions given in https://strictdoc.readthedocs.io/en/latest/StrictDoc.html#installing-strictdoc-as-a-pip-package .

The first issue is trivial: just substitute "git clone git@github.com:stanislaw/strictdoc.git && cd strictdoc" with "git clone https://github.com/strictdoc-project/strictdoc.git && cd strictdoc" (also in the section about installation with Poetry).

Then I got the following:

roberto@vivo:/usr/local/distrib/strictdoc(master)$ python3 strictdoc/cli/main.py
Traceback (most recent call last):
  File "strictdoc/cli/main.py", line 10, in <module>
    from strictdoc.core.actions.export_action import ExportAction
  File "strictdoc/cli/../../strictdoc/core/actions/export_action.py", line 7, in <module>
    from strictdoc.export.excel.excel_generator import ExcelGenerator
  File "strictdoc/cli/../../strictdoc/export/excel/excel_generator.py", line 5, in <module>
    import xlsxwriter
ModuleNotFoundError: No module named 'xlsxwriter'

I installed 'xlsxwriter' successfully, then I got:
roberto@vivo:/usr/local/distrib/strictdoc(master)$ python3 strictdoc/cli/main.py
Traceback (most recent call last):
  File "strictdoc/cli/main.py", line 10, in <module>
    from strictdoc.core.actions.export_action import ExportAction
  File "strictdoc/cli/../../strictdoc/core/actions/export_action.py", line 8, in <module>
    from strictdoc.export.html.html_generator import HTMLGenerator
  File "strictdoc/cli/../../strictdoc/export/html/html_generator.py", line 22, in <module>
    from strictdoc.export.html.tools.html_embedded import HTMLEmbedder
  File "strictdoc/cli/../../strictdoc/export/html/tools/html_embedded.py", line 3, in <module>
    import bs4
ModuleNotFoundError: No module named 'bs4'

After installing 'bs4' I got a similar error for 'datauri'.
Then:

roberto@vivo:/usr/local/distrib/strictdoc(master)$ sudo -H pip install datauri
Collecting datauri
  Downloading datauri-1.0.0-py3-none-any.whl (3.6 kB)
Installing collected packages: datauri
Successfully installed datauri-1.0.0
roberto@vivo:/usr/local/distrib/strictdoc(master)$ python3 strictdoc/cli/main.py
Traceback (most recent call last):
  File "strictdoc/cli/main.py", line 10, in <module>
    from strictdoc.core.actions.export_action import ExportAction
  File "strictdoc/cli/../../strictdoc/core/actions/export_action.py", line 8, in <module>
    from strictdoc.export.html.html_generator import HTMLGenerator
  File "strictdoc/cli/../../strictdoc/export/html/html_generator.py", line 22, in <module>
    from strictdoc.export.html.tools.html_embedded import HTMLEmbedder
  File "strictdoc/cli/../../strictdoc/export/html/tools/html_embedded.py", line 5, in <module>
    from datauri import DataURI
ImportError: cannot import name 'DataURI' from 'datauri' (/usr/local/lib/python3.8/dist-packages/datauri/__init__.py)

**Comment by stanislaw** [comment]
I have updated the documentation with a number of fixes based on your feedback @RobertoBagnara 👍 

1) clone URL - fixed
2) the `pip install strictdoc` is highlighted as a [recommended installation method](https://strictdoc.readthedocs.io/en/latest/StrictDoc.html#installing-strictdoc-as-a-pip-package-recommended-way).
3) to avoid dependency problems, the `requirements.txt` file is available now in the root of strictdoc folder. Without Poetry, all dependencies should be installed now with `pip install -r requirements.txt`. But as discussed in person, this path has to be followed only when someone wants to check StrictDoc in [developer mode](https://strictdoc.readthedocs.io/en/latest/StrictDoc.html#installing-strictdoc-from-github-developer-mode).
4) `tasks.py` no longer depends on Poetry (thanks for the hint!)

Regarding one of your errors:

> ImportError: cannot import name 'DataURI' from 'datauri' (/usr/local/lib/python3.8/dist-packages/datauri/init.py)

Sometimes Python packages don't have the same name as their main import module. In this case, the package used by StrictDoc is actually `python-datauri`. So installing `python-datauri` would fix the problem.
