### ISSUE TITLE
Include mathjax in HTML template to allow for TeX rendering in exported HTML

### ISSUE THREAD

**Issue by lochsh** [strictdoc-project/strictdoc#443]
It would be great to be able to write TeX in the .sdoc the way that Doorstop allows, see https://doorstop.readthedocs.io/en/latest/reference/item/#example-latex-like-math-expressions

I think this is as simple as including the MathJax scripts in the HTML template, see https://www.mathjax.org/#gettingstarted

Possibly python-markdown-math is required, as mentioned in the Doorstop docs above.

Alternatively, being able to provide your own Jinja template would solve this problem while being more flexible.

**Comment by lochsh** [comment]
Closed by #444

**Comment by stanislaw** [comment]
The new strictdoc's pip 0.0.12 has been released.
