### ISSUE TITLE
Allow images to be displayed in output

### ISSUE THREAD

**Issue by lochsh** [strictdoc-project/strictdoc#445]
It's not clear to me from the strictdoc docs how I might include a supporting image in my requirements. If this is not possible, it would certainly be useful to have.

Perhaps the syntax for doing so could look something like this:

```
[IMAGE]
PATH: ../path/to/image.svg
ALT: "A description of the image"
WIDTH: 50
HEIGHT: 80
```
It would be useful to be able to have this within a FREETEXT section, or a REQUIREMENT's STATEMENT, COMMENT or RATIONALE.

**Comment by stanislaw** [comment]
Please check this and let us know if this level of support is enough: https://github.com/strictdoc-project/strictdoc/blob/main/developer/sandbox/sandbox.sdoc#L26

**Comment by lochsh** [comment]
My apologies, I hadn't noticed that. I'm trying it out now.

**Comment by lochsh** [comment]
Thank you, that works great. I'm sorry for not noticing it before -- thanks for the quick response!

**Comment by stanislaw** [comment]
A separate demonstration document is planned, but has not been implemented yet. That document will demonstrate all the StrictDoc's features in one place, with how-to instructions. Your question highlights the importance of that document 👍
