### ISSUE TITLE
HTML not being regenerated correctly with multiple SDoc Files

### ISSUE THREAD

**Issue by Relasym** [strictdoc-project/strictdoc#494]
HTML files are only updated if the sdoc is newer than the output file (HTMLGenerator._export_with_performance), however this doesn't cover the case where a new Requirement is linked to an already existing one in another Document.

Steps:
1, FileA.sdoc contains Requirement001
2, export File A.sdoc
3, add a new sdoc: FileB.sdoc contains Requirement002 with REFS: PARENT: Requirement001
4, export both Files

Expected: Requirement001 links to Requirement002 and vice versa
Actual: Requirement001 does not link to Requirement002 since the HTML for FileA was not regenerated

**Comment by Relasym** [comment]
Not fixed, it incorrectly skips recreating the first file: 
Step 'Collect traceability information' start
Step 'Collect traceability information' took: 0.0 sec
Skip: Linking Test A ........................................ 0.00s
Published: Linking Test B ................................... 0.27s
I'll post the testfiles on the discord

**Comment by stanislaw** [comment]
Thanks again for checking this. I have pushed the second commit that complements the first one. Now the parents are regenerated when a child is changed.
