### ISSUE TITLE
Dockerized strictdoc

### ISSUE THREAD

**Issue by fkromer** [strictdoc-project/strictdoc#562]
Would be great to have a dockerized version of strictdoc similar to https://github.com/doorstop-dev/docker-doorstop .

**Comment by stanislaw** [comment]
I fully support having a dockerized version of strictdoc even though I would not use it myself. The contents of the Dockerfile seem to be trivial, is this something you could contribute?

I don't think this Dockerfile needs a separate repository so I would say go ahead and open a PR right here.

**Comment by fkromer** [comment]
> The contents of the Dockerfile seem to be trivial, is this something you could contribute?

I'll have a look into this.

> I don't think this Dockerfile needs a separate repository so I would say go ahead and open a PR right here.

I agree.
