### ISSUE TITLE
Homebrew packaging

### ISSUE THREAD

**Issue by fkromer** [strictdoc-project/strictdoc#578]
The go-to packaging format for MacOS is [Homebrew](https://brew.sh/). There are [instructions in the docs how to package a Python app](https://docs.brew.sh/Python-for-Formula-Authors). An exemplary formula (declarative way of defining a package) for a Python app is e.g. [Ansible](https://github.com/Homebrew/homebrew-core/blob/7527ce94c312553c3a199f6419bc0302f50b401f/Formula/ansible.rb). All brew packages installable via `brew install <package>` seem to be declared in [`homebrew/homebrew-core/Formula/`](https://github.com/Homebrew/homebrew-core/tree/7527ce94c312553c3a199f6419bc0302f50b401f/Formula). How to [create a package and submit it to homegrew-core is explained here](https://github.com/simonw/til/blob/main/homebrew/packaging-python-cli-for-homebrew.md). The [related git repo is here](https://github.com/simonw/homebrew-datasette).

**Comment by fkromer** [comment]
@stanislaw

Could you cross-check installing `strictdoc` via `brew` like this: `brew tap fkromer/strictdoc`

Clones the repo into `/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/fkromer/homebrew-strictdoc`.

Changedir into `./homebrew-strictdoc` and checkout the `homebrew` branch: `git checkout homebrew`

Install via `brew install fkromer/strictdoc`.

**Comment by fkromer** [comment]
@stanislaw  Being able to test the brew packaging depends on https://github.com/strictdoc-project/strictdoc/issues/583 (output of version).

**Comment by fkromer** [comment]
@stanislaw I figured out that it's easiest to provide a brew package for `strictdoc` via a third party package repository ([tap](https://docs.brew.sh/Taps)). This requires that the formula is defined in a separate repository sticking to a [predefined naming convention](https://docs.brew.sh/Taps#repository-naming-conventions-and-assumptions) (`homebrew-strictdoc`). I'll move the code into a separate repository. If you want to we can move the repo into a repo in the `strictdoc-project` organization namespace later. Using a tap has the advantage that one does not have to satisfy [all requirements required for a formula to be accepted for inclusion into `homebrew-core`](https://docs.brew.sh/Acceptable-Formulae).

**Comment by stanislaw** [comment]
Yes, a separate repo sounds fine. Let me know if I need to do anything to create or move this repository to `strictdoc-project` organization.

**Comment by stanislaw** [comment]
Closing this for the time being. For the context, see https://github.com/strictdoc-project/strictdoc/pull/579#issuecomment-1040739274.
