### ISSUE TITLE
Feature: Exporting and importing requirement subsets of a document

### ISSUE THREAD

**Issue by mnaderhirn** [strictdoc-project/strictdoc#601]
I tried to find an answer if I can write requirements in different files, but could not find an answer

I have the following set of requirements
-	REQ001
-	REQ002
-	REQ003
o	REQ003.001
	TEST-REQ003.001.0001
	TEST-REQ003.001.0002
	TEST-REQ003.001.0003
	TEST-REQ003.001.0004
o	REQ003.002
	TEST-REQ003.002.0001
	TEST-REQ003.002.0002
	TEST-REQ003.002.0003
o	REQ003.003
-	REQ004
o	REQ004.001
o	REQ004.002

In order to work/communicate with potential collaborators, I would like to exchange some of the requirements REQ003.001 to REQ003.003, but not the rest since this is my companies knowhow. They should be able to edit them and send me feedback or implement them.
Another use case is that I ll would like to give the TEST-REQ003.001.0001 to TEST-REQ003.001.0004 to someone outside of my organization for implementation

I think it would be beneficial if I would be able to export the selected requirements to a separate reqif or sdoc file which then can be exchanged with someone maybe with selected fields. Think this is not possible yet or?

Assuming someone did some changes on this set of requirements or added some new onces, it should be possible to reintegrate them into sdoc file either 
-	If already existing to see the difference
-	If not existing to allow to place them somewhere in the document where the editor wants them to be

**Comment by stanislaw** [comment]
After almost 2 years since this ticket had been created, this feature has been released today:

https://strictdoc.readthedocs.io/en/latest/strictdoc_01_user_guide.html#search-and-filtering
https://strictdoc.readthedocs.io/en/latest/strictdoc_04_release_notes.html#id1
