### ISSUE TITLE
Can we update to newer jinja2?

### ISSUE THREAD

**Issue by lochsh** [strictdoc-project/strictdoc#622]
The `pyproject.toml` specifies `jinja2 = "^2.11.2"` for jinja2. There's now a new major version of jinja2, and the tests pass if I upgrade strictdoc to it. Might it make sense to upgrade?

My own personal motivation for this is wanting to use this with a project that requires `jinja2 = "^3.0.3"` but also uses strictdoc. I am not saying that this is motivation for the strictdoc project to change, but it seems like it makes sense to move to a more up to date version if it still meets the project's needs.

I can fix my own personal problem in other ways if not.

**Comment by lochsh** [comment]
It turns out the new release of Jinja2 has caused problems for people, see this issue https://github.com/pallets/jinja/issues/1585#issuecomment-1043892628

Basically, Jinja2 v2 is now end-of-life/unsupported. When they specify their dependencies, they only specify a minimum version, not a maximum. But Jinja2 v2.11 is not compatible with newer versions of `markupsafe`. The maintainers don't want to change it as it's no longer supported.

Anyway -- perhaps strictdoc's pyproject.toml could say `jinja2 = ">=2.11.2,<4.0"?

**Comment by stanislaw** [comment]
@lochsh we can certainly relax the `pyproject.toml`'s requirement. Could you suggest a Pull Request? If yes, in addition to adding the necessary chance to the toml file, please also run this command locally: `invoke export-pip-requirements` - it makes Poetry to generate the requirements.txt file that is used by the Windows CI.

**Comment by lochsh** [comment]
I'll do so now :)

I noticed the version in the pyproject.toml is 0.0.11, should it be 0.0.19?

**Comment by stanislaw** [comment]
The new package 0.0.20 has been released. Thank you for your feedback and contribution.
