### ISSUE TITLE
Hello World example seems broken

### ISSUE THREAD

**Issue by palandro** [strictdoc-project/strictdoc#641]
First cloned strictdoc using 

pip install strictdoc

Then, the Hello World example on 

https://strictdoc.readthedocs.io/en/stable/strictdoc.html#examples

requires a missing dependency.

**Python version**
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32

**Clone and build log**
C:\Users\peter>git clone --depth 1 https://github.com/strictdoc-project/strictdoc && cd strictdoc
Cloning into 'strictdoc'...
remote: Enumerating objects: 687, done.
remote: Counting objects: 100% (687/687), done.
remote: Compressing objects: 100% (562/562), done.
remote: Total 687 (delta 107), reused 453 (delta 64), pack-reused 0
Receiving objects: 100% (687/687), 17.92 MiB | 4.33 MiB/s, done.
Resolving deltas: 100% (107/107), done.
Checking out files: 100% (559/559), done.

C:\Users\peter\strictdoc>strictdoc export docs/
Traceback (most recent call last):
  File "c:\users\peter\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\peter\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\peter\AppData\Local\Programs\Python\Python36\Scripts\strictdoc.exe\__main__.py", line 5, in <module>
  File "c:\users\peter\appdata\local\programs\python\python36\lib\site-packages\strictdoc\cli\main.py", line 14, in <module>
    from strictdoc.commands.version_command import VersionCommand
  File "c:\users\peter\appdata\local\programs\python\python36\lib\site-packages\strictdoc\commands\version_command.py", line 3, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'

C:\Users\peter\strictdoc\strictdoc>pip install toml
Collecting toml
  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Installing collected packages: toml
Successfully installed toml-0.10.2

C:\Users\peter\strictdoc>strictdoc export docs/
Parallelization: Enabled
Step 'Export' start
Step 'Find and read SDoc files' start
Reading SDOC: strictdoc.sdoc ................................ 2.40s
Step 'Find and read SDoc files' took: 3.0 sec
Step 'Collect traceability information' start
Step 'Collect traceability information' took: 0.01 sec
creating C:\Users\peter\strictdoc\output\html\_static
copying c:\users\peter\appdata\local\programs\python\python36\lib\site-packages\strictdoc/export/html/_static\favicon.ico -> C:\Users\peter\strictdoc\output\html\_static
copying c:\users\peter\appdata\local\programs\python\python36\lib\site-packages\strictdoc/export/html/_static\jquery.min.js -> C:\Users\peter\strictdoc\output\html\_static
copying c:\users\peter\appdata\local\programs\python\python36\lib\site-packages\strictdoc/export/html/_static\pan-with-space.js -> C:\Users\peter\strictdoc\output\html\_static
copying c:\users\peter\appdata\local\programs\python\python36\lib\site-packages\strictdoc/export/html/_static\requirements-coverage.js -> C:\Users\peter\strictdoc\output\html\_static
copying c:\users\peter\appdata\local\programs\python\python36\lib\site-packages\strictdoc/export/html/_static\source-code-coverage.js -> C:\Users\peter\strictdoc\output\html\_static
copying c:\users\peter\appdata\local\programs\python\python36\lib\site-packages\strictdoc/export/html/_static\toc.js -> C:\Users\peter\strictdoc\output\html\_static
copying c:\users\peter\appdata\local\programs\python\python36\lib\site-packages\strictdoc/export/html/_static\_base.css -> C:\Users\peter\strictdoc\output\html\_static
copying c:\users\peter\appdata\local\programs\python\python36\lib\site-packages\strictdoc/export/html/_static\_content.css -> C:\Users\peter\strictdoc\output\html\_static
copying c:\users\peter\appdata\local\programs\python\python36\lib\site-packages\strictdoc/export/html/_static\_element.css -> C:\Users\peter\strictdoc\output\html\_static
copying c:\users\peter\appdata\local\programs\python\python36\lib\site-packages\strictdoc/export/html/_static\_layout.css -> C:\Users\peter\strictdoc\output\html\_static
copying c:\users\peter\appdata\local\programs\python\python36\lib\site-packages\strictdoc/export/html/_static\_requirement-tree.css -> C:\Users\peter\strictdoc\output\html\_static
copying c:\users\peter\appdata\local\programs\python\python36\lib\site-packages\strictdoc/export/html/_static\_requirement.css -> C:\Users\peter\strictdoc\output\html\_static
copying c:\users\peter\appdata\local\programs\python\python36\lib\site-packages\strictdoc/export/html/_static\_source.css -> C:\Users\peter\strictdoc\output\html\_static
copying c:\users\peter\appdata\local\programs\python\python36\lib\site-packages\strictdoc/export/html/_static\_tree.css -> C:\Users\peter\strictdoc\output\html\_static
Published: StrictDoc ........................................ 4.30s
Export completed. Documentation tree can be found at:
C:\Users\peter\strictdoc\output\html
Step 'Export' took: 9.14 sec

**Comment by stanislaw** [comment]
Hi @palandro ,

Thank you for reporting this.

This is one of the known issues that should go away when I finish fighting with Windows here: https://github.com/strictdoc-project/strictdoc/pull/640. After that change, strictdoc will always be built from a clean Python environment.

Otherwise, it was easy for me to miss the fact that the toml was not properly configured in the dependencies and the code was passing locally as well as on the CI.

For now, please install the toml manually. In the linked pull request, the dependency on toml is being removed, so I would not issue a hotfix for this already.
