### ISSUE TITLE
Jinja2 template not fount (HTML export)

### ISSUE THREAD

**Issue by gioboske** [strictdoc-project/strictdoc#652]
Starting from release 0.0.22 (and including pre-release 0.0.23a1), loading Jinja2 templates raises a `TemplateNotFound` exception.

When installing `strictdoc` from PyPI or (testPyPI) the template and static folders are not stored together with the package sources (e.g. referring to Python 3.9 official Docker image, it is stored in `/usr/local/strictdoc/export/html/` instead of  `/usr/local/lib/python3.9/site-packages/strictdoc/export/html/`).

Manually moving the folders solves the issue.

**Comment by stanislaw** [comment]
The issue should be fixed now and I have released the [0.0.23](https://pypi.org/project/strictdoc/0.0.23/).

It would be great if you could check it on your side.

**Comment by gioboske** [comment]
> The issue should be [fixed](https://github.com/strictdoc-project/strictdoc/issues/652) now and I have released the [0.0.23](https://pypi.org/project/strictdoc/0.0.23/).
> 
> It would be great if you could check it on your side.

Everything works correctly, issue solved. :thumbsup:
Just one note: the new release is tagged as 0.0.23, but the changelog in the release notes points to the diff between 0.0.21 and 0.0.22, instead.
