### ISSUE TITLE
Problem with Pyinstaller

### ISSUE THREAD

**Issue by Abramo-Bagnara** [strictdoc-project/strictdoc#740]
I am trying to package strictdoc using Pyinstaller.
The command I use under Linux, after I have cloned the repository under `${HOME}/strictdoc`,  is the following:

> #!/bin/sh
DIST="/tmp/strictdoc"
rm -rf "${DIST}"
mkdir -p "${DIST}"
"${HOME}/.local/bin/pyinstaller" \
    --clean \
    -n strictdoc \
    -y --distpath "${DIST}" \
    "${HOME}/strictdoc/strictdoc/cli/main.py"

Then:

> /tmp/strictdoc$ ./strictdoc/strictdoc export /tmp/test.sdoc
Parallelization: Enabled
Step 'Collect traceability information' start
Traceback (most recent call last):
  File "strictdoc/cli/main.py", line 110, in <module>
  File "strictdoc/cli/main.py", line 104, in main
  File "strictdoc/cli/main.py", line 102, in main
  File "strictdoc/cli/main.py", line 64, in _main
  File "strictdoc/core/actions/export_action.py", line 26, in build_index
  File "strictdoc/helpers/timing.py", line 14, in wrap
  File "strictdoc/core/traceability_index_builder.py", line 47, in create
ValueError: max() arg is an empty sequence
[359744] Failed to execute script 'main' due to unhandled exception!

The line in question is the following:

> latest_strictdoc_own_file = max(strict_own_files, key=os.path.getctime)

I think the issue is the one described here: [https://stackoverflow.com/questions/404744/determining-application-path-in-a-python-exe-generated-by-pyinstaller](url)

That page contains also the solution to the problem. However, it seems to me there are other places where strictdoc makes assumptions about its installation directory and technology, such as in the first part of `main.py`, so I am not sure what the proper fix might be.

**Comment by stanislaw** [comment]
Hi @Abramo-Bagnara,

thanks for reporting this. I should be able to check this issue within a couple of days.

The line that you are reporting has to do with the code that should work only during development - I wanted to hide it under a command line argument to disable it in the released Python packages but didn't get to doing it yet. I will also check other places where strictdoc might be making assumptions about its own directory.

**Comment by stanislaw** [comment]
The PyInstaller seems to work now, however I see two further issues that are not entirely clear to me yet:

1) I don't understand how PyInstaller decides which third-party pip packages it includes to the binary:

If I run it from a virtual environment which has all StrictDoc dependencies installed, the binary works. If I run PyInstaller from a clear virtual environment, the resulting binary starts to miss these third-party packages. I have not used PyInstaller before, and without knowing how it works, this implicit behavior seems to be quite strange.

2) A more annoying issue: I have tried the binary built on one macOS on another macOS: the other macOS started to complain about the lack of the code signing identity as well as it was prompting about user to give permissions to use **every** dynamic library which was produced by the PyInstaller. This issue needs further investigation.

----

Try this sequence of commands:

```
invoke release-pyinstaller
invoke invoke test-integration --strictdoc /tmp/strictdoc/strictdoc/strictdoc
```

If both commands work, then you have the same results that I have at this point.

**Comment by stanislaw** [comment]
Regarding the first of the above two issues:

This link suggests that PyInstaller is quite greedy in capturing the current virtual environment as well as some of the Python standard libraries: https://stackoverflow.com/a/55312484/598057.

The folder size is `39M` with development dependencies excluded and `40M` when they are included. This should be good enough for now.

Note that another alternative to PyInstaller is `cx_Freeze`, see another answer in the same SO thread.
