### ISSUE TITLE
pip image for 0.0.27 missing requirements.txt

### ISSUE THREAD

**Issue by eddlestar** [strictdoc-project/strictdoc#751]
Appears that the pip package for 0.0.27 is missing some files (namely requirements.txt). Was able to revert to 0.0.26 and had no problems building.

**Comment by stanislaw** [comment]
Thanks a lot for reporting this! I know exactly where to look for the issue 😄

**Comment by stanislaw** [comment]
Could you try installing again? The issue should be fixed now.
