### ISSUE TITLE
Document file name/url with invisible symbols

### ISSUE THREAD

**Issue by mettta** [strictdoc-project/strictdoc#774]
1.
+ copy file name (url) from the web page (document1.sdoc)
+ input from clipboard, and change some symbols (document2.sdoc)
+ save the file
=> file saved, but does not appear in the tree

2.
+ manually type visible address characters and save the file  (document2.sdoc)
=> file saved, and appears in the tree
=> file saved, but does not appear in the tree

1+2
=> the tree shows only the file with manually entered characters
=> but the directory contains both files

**Comment by stanislaw** [comment]
This has been implemented in:

- https://github.com/strictdoc-project/strictdoc/pull/1481
- https://github.com/strictdoc-project/strictdoc/issues/1330
