### ISSUE TITLE
Can't install 0.0.29 or 0.0.30: requirements.txt missing

### ISSUE THREAD

**Issue by adamgreig** [strictdoc-project/strictdoc#803]
If I try and `pip install strictdoc` for versions 0.0.29 or 0.0.30, I get an error about a missing `requirements.txt`:

```
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-a5hrwvr5/strictdoc_970ff0615c5a4659a740d2099e3e5dba/setup.py", line 23, in <module>
          with open("requirements.txt") as fp:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

It seems like this was meant to be fixed in #752, and indeed 0.0.28 does install fine, while 0.0.27 breaks with the same error. If I download the release files from PyPI, I find 0.0.28 does include a `requirements.txt` file, but it's missing from 0.0.27, 0.0.29, and 0.0.30.

I can't see anything that's changed since 0.0.28 was released that might affect what gets included in the release file though, so maybe it was something particular about how 0.0.28 was packaged?

**Comment by stanislaw** [comment]
Hi @adamgreig, thanks a lot for reporting this! Indeed, the 0.0.28 I released from my PC manually. I have just tried to package the latest main branch locally, and the tar does contain the requirements.txt file.

I will investigate it right now.

**Comment by adamgreig** [comment]
Thanks for the quick response! I checked and I can install 0.0.31a1 just fine, I look forward to trying out the new web server stuff. Makes sense to swap to `pyproject.toml` to fix this properly though.

**Comment by adamgreig** [comment]
0.0.31 installs fine, thanks!

**Comment by stanislaw** [comment]
Yeah, the migration seems to have gone well! Thanks for letting me to concentrate on exactly this long-standing issue 😄 

Regarding the server work - it is still pretty early, but the overall architecture with FastAPI/Hotwire is working just fine and more UI improvements are coming.
