### ISSUE TITLE
Ensure a convention for the custom fields: single-line fields above, multiline fields below

### ISSUE THREAD

**Issue by mettta** [strictdoc-project/strictdoc#948]
Now the custom field is displayed in different places in the requirement layout, depending on the CONTENT LENGTH:
1) or in a table with meta-information, 
2) or under the comments.
This is counterintuitive.

**Comment by stanislaw** [comment]
We have implemented this convention here: https://github.com/strictdoc-project/strictdoc/commit/6174d63fab0f10d0faf611436d083ac23c123195.
