### ISSUE TITLE
File Traceability: Highlight issues when tagging ranges outside of one of the referenced files

### ISSUE THREAD

**Issue by gustavokerezi** [strictdoc-project/strictdoc#990]
I noticed when referencing 2 files in a single requirement, if the 'larger file' is declared first in the REQUIREMENT REFS, and the range of code that is marked on the code for the large file is outside the range of the smaller file, the highlighting for the smaller file on the source coverage stops working, due to an [error](https://github.com/strictdoc-project/strictdoc/blob/93d9081559a2f648e1e996ab8b6820eb464806ae/docs/strictdoc-html/strictdoc-html/_static/source-code-coverage.js#L363):
![image](https://user-images.githubusercontent.com/3150144/223880576-e7426b44-1a31-4e99-a296-0110bae3cf31.png)

Steps to replicate:
req.sdoc
```code
[DOCUMENT]
TITLE: TEST DOCUMENT

[REQUIREMENT]
UID: REQ-01
REFS:
- TYPE: File
  VALUE: large_file.py
- TYPE: File
  VALUE: small_file.py
TITLE: Test_REQ
STATEMENT: >>>
Declaring a large file range tagged before a small file breaks highlighting
<<<
```
small_file.py
```python
import os

# [REQ-01]
def tiny_function():    
    return 1+1
 # [/REQ-01]

tiny_function()
```
large_file.py
```python
import os


def large_function():
    #
    #
    #
    #
    #
    #
    #
    #
    #
    #
    #
    # [REQ-01]
    a = 1
    # [/REQ-01]
    #
    #
    #
    return a+1


large_function()
```

Built with 0.0.32 / 0.0.33 using:
```code
strictdoc export . --experimental-enable-file-traceability
````

When inverting the order in the requirement definition, it stops failing, however both ranges are highlighted in the large_file:
```code
[REQUIREMENT]
UID: REQ-01
REFS:
- TYPE: File
  VALUE: small_file.py
- TYPE: File
  VALUE: large_file.py
```
![image](https://user-images.githubusercontent.com/3150144/223881279-7fbb548e-a575-40f9-9fda-c5cc36f69472.png)

**Comment by stanislaw** [comment]
@mettta, I have included an integration test that reproduces this bug report's setup: https://github.com/strictdoc-project/strictdoc/tree/main/tests/integration/commands/export/html/file_traceability/14_user_report_larger_file.

**Comment by stanislaw** [comment]
@gustavokerezi could you try the alpha version here:

```
pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple strictdoc==0.0.34a1
```

I believe that your issue should be fixed now.
